#############################################
# Active Providers
#############################################
[providers]
active = ["openai"] # first one is the default

[provider_labels]
openai      = "OpenAI"

#############################################
# Provider Configurations
#############################################


[openai]
api_key   = ""
model     = "gpt-4o"
base_url  = "https://api.openai.com/v1"
